accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #path('', views.home, name='home'),
    

    path('', views.login_municipe_view, name='login_municipe'),
    path('login_prefeitura/', views.login_prefeitura, name='login_prefeitura'),
    
    path('painel_solicitacoes_municipe/', views.painel_solicitacoes_municipe, name='painel_solicitacoes_municipe'),
    path('painel_solicitacoes_prefeitura/', views.painel_solicitacoes_prefeitura, name='painel_solicitacoes_prefeitura'),
    
    path('atualizar_status/<int:id>/<str:status>/', views.atualizar_status, name='atualizar_status'),
    path('atualizar_prioridade/<int:id>/<str:prioridade>/', views.atualizar_prioridade, name='atualizar_prioridade'),
    path('sucesso/<int:id>/', views.solicitacoes_municipe_sucesso, name='solicitacoes_municipe_sucesso'),

    path('register_municipe/', views.register_municipe, name='register_municipe'),
    
    path('password_reset/', views.password_reset_request, name='password_reset')
    
    
]

[
    # Envio de reset de senha 
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name='password_reset_complete'),
         
]

piunivesp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')), 
]

# Mostra imagem ao clicar no botão ver imagem

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

accounts/models.py
from django.db import models

# Create your models here.


class Usuario(models.Model):
    register_prefeitura = models.CharField(max_length=50)
    coluna_1234 = models.CharField(max_length=50)
    

# solicitacoes/models.py


class Solicitacao(models.Model):
    #id_Solicitacoes = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=255, blank=True, null=True)
    endereco = models.CharField(max_length=255)
    email = models.EmailField()
    mensagem = models.TextField()
    imagem = models.ImageField(upload_to='imagens/', blank=True, null=True)
    status = models.CharField(
        max_length=20,
        choices=[
            ('em aberto', 'Em Aberto'),
            ('pendente', 'Pendente'),
            ('finalizado', 'Finalizado')
        ],
        default='em aberto'
    )
    data_abertura = models.DateTimeField(auto_now_add=True)
    tipo_solicitacao = models.CharField(
        max_length=20,
        choices=[
            ('manutencao', 'Manutenção'),
            ('outra_opcao', 'Outra Opção'),
            ('mais_uma_opcao', 'Mais Uma Opção')
        ],
        default='manutencao'
    )
    prioridade = models.CharField(
        max_length=20,
        choices=[
            ('minima', 'Mínima'),
            ('maxima', 'Máxima')
        ],
        default='minima'
    )

    class Meta:
        db_table = 'dados_solicitacoes'

    def __str__(self):
        return f"{self.nome} - {self.endereco}"

accounts/forms.py
from django import forms
from .models import Usuario
from .models import Solicitacao          

# Log in prefeitura

class RegistroForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['register_prefeitura', 'coluna_1234']
        widgets = {
            'coluna_1234': forms.PasswordInput(),
        }

# Formulário munícipe

class SolicitacaoForm(forms.ModelForm):
    mensagem = forms.CharField(widget=forms.Textarea(attrs={'maxlength': '50'}))

    class Meta:
        model = Solicitacao
        fields = ['nome', 'endereco', 'email', 'mensagem', 'imagem', 'tipo_solicitacao', 'prioridade']        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView
from django.core.exceptions import ValidationError
from django.db.models import Q  
from .models import Usuario
from .forms import SolicitacaoForm
from .models import Solicitacao


def register_municipe(request):
    context = {}
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        try:
            if User.objects.filter(username=email).exists():
                raise ValidationError("Este e-mail já está em uso.")
            else:
                User.objects.create_user(username=email, password=password)
        except ValidationError as e:
            context['error'] = str(e)
    return render(request, 'register_municipe.html', context)


def login_municipe_view(request):
    if request.method == 'POST':
        email = request.POST['email']  
        password = request.POST['password']
        user = authenticate(request, username=email, password=password) 
        if user is not None:
            login(request, user)
            return redirect('painel_solicitacoes_municipe')  # Redireciona para a página 'painel_solicitacoes_municipe'
    return render(request, 'login_municipe.html')

def painel_solicitacoes_municipe(request):
    return render(request, 'painel_solicitacoes_municipe.html')

def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "password/password_reset_email.txt"
                    c = {
                    "email":user.email,
                    'domain':'127.0.0.1:8000',
                    'site_name': 'Website',
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "user": user,
                    'token': default_token_generator.make_token(user),
                    'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect ("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="password/password_reset.html", context={"password_reset_form":password_reset_form})



def login_prefeitura(request):
    return render(request, 'login_prefeitura.html')

def login_prefeitura(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.username == 'prefeitura1':
                login(request, user)
                return redirect('painel_solicitacoes_prefeitura')
            else:
                return render(request, 'login_prefeitura.html', {'error': 'Senha ou usuário incorretos'})
        else:
            return render(request, 'login_prefeitura.html', {'error': 'Senha ou usuário incorretos'})
    return render(request, 'login_prefeitura.html')

def painel_solicitacoes_prefeitura(request):
    return render(request, 'painel_solicitacoes_prefeitura.html')


# solicitacoes/views

def painel_solicitacoes_municipe(request):
    if request.method == 'POST':
        form = SolicitacaoForm(request.POST, request.FILES)
        if form.is_valid():
            nova_solicitacao = form.save()  # Guarde a instância do objeto criado
            return redirect('solicitacoes_municipe_sucesso', id=nova_solicitacao.id)  # Passe o ID como um argumento
    else:
        form = SolicitacaoForm()
    return render(request, 'painel_solicitacoes_municipe.html', {'form': form})

def painel_solicitacoes_prefeitura(request):
    solicitacoes = Solicitacao.objects.all()
    return render(request, 'painel_solicitacoes_prefeitura.html', {'solicitacoes': solicitacoes})

def atualizar_status(request, id, status):
    solicitacao = Solicitacao.objects.get(id=id)
    solicitacao.status = status
    solicitacao.save()
    return redirect('painel_solicitacoes_prefeitura')

def atualizar_prioridade(request, id, prioridade):
    solicitacao = Solicitacao.objects.get(id=id)
    solicitacao.prioridade = prioridade
    solicitacao.save()
    return redirect('painel_solicitacoes_prefeitura')

def solicitacoes_municipe_sucesso(request, id):  
    return render(request, 'solicitacoes_municipe_sucesso.html', {'id': id})  

accounts/templates/login_municipe.html
<!--

Esta página de login do usuário munícipe na plataforma para solicitações a prefeitura

Falta trabalhar no css

-->

<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f0f0f0;
        }

        form {
            display: flex;
            flex-direction: column;
            width: 300px;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            background-color: #fff;
        }

        input[type="submit"] {
            margin-top: 10px;
        }

        a {
            margin-top: 10px;
            text-decoration: none;
            color: blue;
        }

        .error {
            color: red;
        }

        .titulo {
            position: absolute;
            top: 10px;
            left: 50%;
            transform: translateX(-50%);
            font-size: 54px;
            font-weight: bold;
        }

        /* Adicione o seguinte estilo CSS */
        .botao-direito {
            position: absolute;
            top: 10px;
            right: 10px;
        }

        /* Adicione o seguinte estilo CSS para o botão */
        .botao-direito button {
            font-size: 24px; /* Aumenta o tamanho da fonte */
            padding: 10px 20px; /* Adiciona padding ao botão */
        }
    </style>
</head>
<body>
    <div class="titulo">Guardiões urbanos</div>

    <!-- Adiciona o botão Acesso prefeitura -->
    <div class="botao-direito">
        <button onclick="window.location='{% url 'login_prefeitura' %}'" type="button">Acesso prefeitura</button>
    </div>

    <form method="post">
        {% csrf_token %}
        <label for="email">E-mail:</label><br>
        <input type="email" id="email" name="email" required><br>
        <label for="password">Senha:</label><br>
        <input type="password" id="password" name="password" required><br>
        {% if error %}
            <p class="error">{{ error }}</p>
        {% endif %}
        <input type="submit" value="Iniciar sessão">
        <a href="{% url 'register_municipe' %}">Criar uma conta</a>
        <a href="{% url 'password_reset' %}">Esqueceu sua senha?</a>
    </form>
</body>
</html>

accounts/templates/login_prefeitura.html
<!--

Esta página de login do usuário da prefeitura para acesso a plataforma de solicitações abertas pelos munícipes

Falta trabalhar no css

-->


<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f0f0f0;
        }

        form {
            display: flex;
            flex-direction: column;
            width: 300px;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            background-color: #fff;
        }

        input[type="submit"], button.voltar {
            margin-top: 10px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            cursor: pointer;
        }

        button.voltar {
            background-color: #e7e7e7;
            color: black;
        }

        a {
            margin-top: 10px;
            text-decoration: none;
            color: blue;
        }

        .error {
            color: red;
        }

        .titulo {
            position: absolute;
            top: 10px;
            left: 50%;
            transform: translateX(-50%);
            font-size: 54px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="titulo">Acesso painel prefeitura</div>

    <form method="post">
        {% csrf_token %}
        <label for="username">Nome de usuário:</label><br>
        <input type="text" id="username" name="username" required><br>
        <label for="password">Senha:</label><br>
        <input type="password" id="password" name="password" required><br>
        {% if error %}
            <p class="error">{{ error }}</p>
        {% endif %}
        <input type="submit" value="Iniciar sessão">
        <!-- Botão Voltar adicionado abaixo do botão Iniciar sessão -->
        <button type="button" class="voltar" onclick="window.history.back();">Voltar</button>
    </form>
</body>
</html>

accounts/templates/painel_solicitacoes_municipe.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="">
    <meta name="description" content="solicitação_prefeitura_indaiatuba">
    <meta name="keywords" content="solicitação, prefeitura indaiatuba, manutenção">
    <title>Guardiões Urbanos | Prefeitura de Indaiautba  </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/checkout/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  
    <link href="form-validation.css" rel="stylesheet">
  </head>
  <body class="bg-light">
    
<div class="container">
  <main>
    <div class="py-5 text-center">
      {% load static %}
      <img class="d-block mx-auto mb-4" src="{% static 'images/prefeitura.png' %}" alt="prefeitura de indaiatuba" width="480" height="200">
      
      <h2>Guardiões Urbanos</h2>
      <p class="lead">Guardiões urbanos, é um serviço de zeladoria da cidade de forma online, onde com a cooperação do cidadão é solicitado serviços na sua rua ou em seu bairro, de um jeito mais fácil e rápido.
        Preencha os campos abaixo:
      </p>
    </div>
    <div class="col-md-5">
      <label for="country" class="form-label">Solicitação</label>
      <select class="form-select" id="country" required>
        <option value="">Manutenção</option>
        <option>Andamento</option>
        <option>Reclamação</option>
      </select>
    </div>
    <div class="col-md-7 col-lg-8">
        
        <form class="needs-validation" novalidate>
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">Nome</label>
              <input type="text" class="form-control" id="firstName" placeholder="Nome completo" value="" required>
              <div class="invalid-feedback">
              </div>
            <div class="col-12">
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Endereço da Solicitação</label>
              <input type="text" class="form-control" id="address" placeholder="nome da rua e numero" required>
              <div class="invalid-feedback">
              </div>
            </div>
           
            <div class="form-inline">
              <label for="zip" class="form-label">Escreva a solicitação:</label>
                 
                <label for="exampleFormControlTextarea1" class="form-label"></label>
                <textarea class="form-control" id="caixadetexto" rows="6" style="width: 500px;" placeholder="escreva aqui" required></textarea>
              </div>
              <div class="invalid-feedback">
            </div>
            </div>
          </div>

     <br>

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="same-address">
            <label class="form-check-label" for="same-address">Receber andamento do processo</label>
          </div>
          <br><br>
          <div class="input-group mb-3">
            <input type="file" class="form-control" id="inputGroupFile02">
            <label class="input-group-text" for="inputGroupFile02">Upload</label>
          </div>
          
 

        <br>
        <br>

          <button class="w-100 btn btn-primary btn-lg" type="submit">Enviar</button>
        </form>
      </div>
    </div>
  </main>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      <script src="form-validation.js"></script>
  </body>
</html>

accounts/templates/painel_solicitacoes_municipe1.html
<!--

Estya página serve para os munícipes preencher as solicitações a prefeitura para manutenção, aluguel de espaço público etc...

-->

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Painel de Solicitações</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
            border-radius: 8px;
            margin-top: 40px;
        }
        h1 {
            text-align: center;
            color: #333;
            font-size: 1.5em; 
        }
        form {
            display: flex;
            flex-direction: column;
            align-items: flex-start; 
        }
        form > * {
            margin-bottom: 15px;
        }
        textarea {
            height: 50px; 
        }
        input[type="text"], input[type="email"], textarea, input[type="file"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        button {
            width: 200px;
            padding: 10px;
            border: none;
            border-radius: 4px;
            background-color: #28a745;
            color: white;
            font-size: 18px;
            cursor: pointer;
        }
        button:hover {
            background-color: #218838;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Enviar Solicitação</h1>
        <form method="post" action="{% url 'painel_solicitacoes_municipe' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enviar</button>
        </form>
    </div>
</body>
</html>

accounts/templates/painel_solicitacoes_prefeitura.html
<!-- Estya página serve para a prefeitura realizar as tratativas -->

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Painel da Prefeitura</title>
    <style>
        .status-menu, .prioridade-menu {
            display: none;
            position: absolute;
            background-color: white;
            border: 1px solid black;
            min-width: 100px;
            left: 50%;
            transform: translateX(-306%);
        }
        .status-menu a, .prioridade-menu a {
            display: block;
            padding: 5px;
            text-decoration: none;
            color: black;
        }
        td.mensagem {
            white-space: pre-wrap;
        }
        /* Adiciona estilos à tabela */
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            cursor: pointer; /* Adiciona o cursor de ponteiro */
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
    <script>
        function toggleStatusMenu(id) {
            var menu = document.getElementById('status-menu-' + id);
            menu.style.display = (menu.style.display === 'block') ? 'none' : 'block';
        }

        function togglePrioridadeMenu(id) {
            var menu = document.getElementById('prioridade-menu-' + id);
            menu.style.display = (menu.style.display === 'block') ? 'none' : 'block';
        }

        function pesquisarPorId() {
            var id = document.getElementById('pesquisa').value;
            var solicitacoes = document.getElementsByClassName('solicitacao');
            for (var i = 0; i < solicitacoes.length; i++) {
                if (solicitacoes[i].id !== 'solicitacao-' + id) {
                    solicitacoes[i].style.display = 'none';
                } else {
                    solicitacoes[i].style.display = '';
                }
            }
        }
    </script>
</head>
<body>
    <h1>Solicitações</h1>
    <input type="text" id="pesquisa" placeholder="Digite o ID para pesquisar">
    <button onclick="pesquisarPorId()">Pesquisar</button>
    <button onclick="location.reload()">Atualizar</button> <!-- Adiciona o botão de atualizar -->
    <table>
        <tr>
            <th>ID</th>            
            <th>Foto</th>
            <th>Data</th>
            <th>Status</th>
            <th>Nome</th>
            <th>Endereço</th>
            <th>Tipo de Solicitação</th>
            <th>Prioridade</th>
            <th>Mensagem</th> 
        </tr>
        {% for solicitacao in solicitacoes %}
        <tr class="solicitacao" id="solicitacao-{{ solicitacao.id }}">
            <td>{{ solicitacao.id }}</td>
            <td>
                {% if solicitacao.imagem %}
                    <a href="{{ solicitacao.imagem.url }}" target="_blank">Ver Imagem</a>
                {% endif %}
            </td>
            <td>{{ solicitacao.data_abertura }}</td>
            <td onclick="toggleStatusMenu({{ solicitacao.id }})">{{ solicitacao.status }} <span>&#9660;</span></td> <!-- Adiciona a seta -->
            <td>{{ solicitacao.nome }}</td>
            <td>{{ solicitacao.endereco }}</td>
            <td>{{ solicitacao.get_tipo_solicitacao_display }}</td>
            <td onclick="togglePrioridadeMenu({{ solicitacao.id }})">{{ solicitacao.prioridade }}</td>
            <td class="mensagem">{{ solicitacao.mensagem }}</td> 
        </tr>
        <tr id="status-menu-{{ solicitacao.id }}" class="status-menu">
            <td colspan="9"> 
                <a href="{% url 'atualizar_status' solicitacao.id 'em aberto' %}">Em Aberto</a>
                <a href="{% url 'atualizar_status' solicitacao.id 'pendente' %}">Pendente</a>
                <a href="{% url 'atualizar_status' solicitacao.id 'finalizado' %}">Finalizado</a>
            </td>
        </tr>
        <tr id="prioridade-menu-{{ solicitacao.id }}" class="prioridade-menu">
            <td colspan="9"> 
                <a href="{% url 'atualizar_prioridade' solicitacao.id 'minima' %}">Mínima</a>
                <a href="{% url 'atualizar_prioridade' solicitacao.id 'maxima' %}">Máxima</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

accounts/templates/password_reset_complete.html
<!--

Este arquivo retorna uma mensagem: Sua senha foi redefinida com sucesso. Você agora pode fazer login com sua nova senha.

Falta trabalhar no css

-->


<!DOCTYPE html>
<html>
<head>
    <title>Redefinição de Senha Completa</title>
</head>
<body>
    <h2>Redefinição de Senha Completa</h2>
    <p>Sua senha foi redefinida com sucesso. Você agora pode fazer login com sua nova senha.</p>
</body>
</html>

accounts/templates/password_reset_confirm.html
<!--

Página de redefinição de senha do usuário munícipe

Falta trabalhar no css

-->

<!DOCTYPE html>
<html>
<head>
    <title>Confirmar Redefinição de Senha</title>
</head>
<body>
    <h2>Confirmar Redefinição de Senha</h2>
    <form action="/confirm-reset-password" method="post">
        <label for="password">Nova Senha:</label><br>
        <input type="password" id="password" name="password" required><br>
        <label for="confirm_password">Confirmar Nova Senha:</label><br>
        <input type="password" id="confirm_password" name="confirm_password" required><br>
        <input type="submit" value="Redefinir Senha">
    </form>
</body>
</html>

accounts/templates/password_reset_done.html
<!--

Este arquivo retorna uma mensagem: Um email foi enviado para o endereço fornecido com instruções para redefinir sua senha.

Falta trabalhar no css e no envio de e-mail de reset

-->

<!DOCTYPE html>
<html>
<head>
    <title>Solicitação Enviada</title>
</head>
<body>
    <h2>Solicitação de Redefinição de Senha Enviada</h2>
    <p>Um email foi enviado para o endereço fornecido com instruções para redefinir sua senha.</p>
</body>
</html>

accounts/templates/register_municipe.html
<!--

Esta pegina serve para registar novos munícipes para acesso a plataforma.

-->

<!DOCTYPE html>
<html>
<head>
    <title>Criar conta</title>
</head>
<body>
    <h2>Criar conta</h2>
    <form method="post">
        {% csrf_token %}
        <label for="email">E-mail:</label><br>
        <input type="email" id="email" name="email" required><br>
        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password" required><br>
        <input type="submit" value="Register">
    </form>
    <a href="{% url 'login_municipe' %}">Já possui uma conta? Acessar</a>
</body>
</html>

accounts/templates/register_prefeitura.html
<form method="post">
    {% csrf_token %}
    <label for="register_prefeitura">Nome de usuário:</label><br>
    <input type="text" id="register_prefeitura" name="register_prefeitura" required><br>
    <label for="coluna_1234">Senha:</label><br>
    <input type="password" id="coluna_1234" name="coluna_1234" required><br>
    {% if error %}
        <p class="error">{{ error }}</p>
    {% endif %}
    <input type="submit" value="Iniciar sessão">
    <!-- Botão Voltar adicionado abaixo do botão Iniciar sessão -->
    <button type="button" class="voltar" onclick="window.history.back();">Voltar</button>
</form>

accounts/templates/solicitacoes_municipe_sucesso.html
<!-- accounts/templates/solicitacoes_municipe_sucesso.html -->

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Sucesso</title>
    <style>
        /* Adiciona estilos ao botão Voltar */
        a {
            display: inline-block;
            padding: 10px 20px;
            text-decoration: none;
            background-color: #007bff;
            color: white;
            border-radius: 4px;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }
        a:hover {
            background-color: #0056b3;
        }
        /* Adiciona estilos à mensagem do ID */
        p.id {
            font-size: 1.5em; /* Aumenta o tamanho da fonte */
            font-weight: bold; /* Torna a fonte em negrito */
        }
    </style>
</head>
<body>
    <h1>Sua solicitação foi enviada com sucesso!</h1>
    <p class="id">O ID da sua solicitação é {{ id }}.</p> <!-- Adicione a classe 'id' aqui -->
    <a href="{% url 'painel_solicitacoes_municipe' %}">Voltar</a>
</body>
</html>